Module2
StanislavMilavitsky/Modules-Epam pull request #1
Opened 2022-02-10 10:39 UTC by StanislavMilavitsky

2022-02-16 14:44 UTC, volynetspavel requested changes

2022-02-16 14:44 UTC, volynetspavel commented on api/src/java/com/epam/esm/configuration/SpringConfig.java
> +    @Profile("prod")
why this is commented?

2022-02-16 14:44 UTC, volynetspavel commented on api/src/java/com/epam/esm/controller/GiftCertificateController.java
> +        return result != -1L ? ResponseEntity.ok("Delete successful!") : ResponseEntity.ok("Delete unsuccessful!");
maybe better create boolean variable the long?

2022-02-16 14:44 UTC, volynetspavel commented on api/src/java/com/epam/esm/controller/GiftCertificateController.java
> +    @GetMapping("/byName/{name}")
is name part of url or name is parameter in url?
check please how to create names for url https://hackernoon.com/restful-api-designing-guidelines-the-best-practices-60e1d954e7c9

2022-02-16 14:44 UTC, volynetspavel commented on api/src/java/com/epam/esm/controller/TagController.java
> +    @PostMapping(value = "/", consumes = "application/json")
is it necessary to have value for one post method? 
why do you need consumes there? does it work without consumes defenition?

2022-02-16 14:44 UTC, volynetspavel commented on api/src/java/com/epam/esm/exception/ControllerException.java
> +public class ControllerException extends Exception {
what is this exception doing?

2022-02-16 14:44 UTC, volynetspavel commented on core/src/main/java/com/epam/esm/service/impl/GiftCertificateServiceImpl.java
> +        GiftCertificate giftCertificate = giftCertificateDAO.read(id);
maybe better check on null before converting to dto?

2022-02-16 14:44 UTC, volynetspavel commented on core/src/main/java/com/epam/esm/service/impl/GiftCertificateServiceImpl.java
> +        if (giftCertificates != null) {
what if list is not null but empty?

2022-02-16 14:44 UTC, volynetspavel commented on core/src/main/java/com/epam/esm/service/impl/GiftCertificateServiceImpl.java
> +            logger.error("Sort by name exception!");
it's not quite an understandable message for the exception, in the message should be the reason: why we we have such exception.

2022-02-16 14:44 UTC, volynetspavel commented on core/src/test/java/com/epam/esm/dao/impl/TagDAOImplTest.java
> +    void delete() {
there is should be also negative tests

2022-02-16 14:44 UTC, volynetspavel commented on core/src/main/java/com/epam/esm/dao/impl/GiftCertificateDAOImpl.java
> +        return rows > 0L ? giftCertificateDTO.getId() : -1L;
there is should be returned updated entity, to see result, that your entity was updated

2022-02-16 14:44 UTC, volynetspavel commented on core/src/main/java/com/epam/esm/dao/impl/GiftCertificateDAOImpl.java
> +    public long update(GiftCertificateDTO giftCertificateDTO)  {
as I see your dao works only with entity, not with dto. would be better use there entity too

2022-02-17 12:52 UTC, StanislavMilavitsky commented on api/src/java/com/epam/esm/configuration/SpringConfig.java
> +    @Profile("prod")
Deleted methods with annotation  Profile

2022-02-17 12:55 UTC, StanislavMilavitsky commented on api/src/java/com/epam/esm/controller/GiftCertificateController.java
> +        return result != -1L ? ResponseEntity.ok("Delete successful!") : ResponseEntity.ok("Delete unsuccessful!");
In response, I preferred to return the id, after which it was possible to work with it if that need

2022-02-17 13:05 UTC, StanislavMilavitsky commented on api/src/java/com/epam/esm/controller/GiftCertificateController.java
> +    @GetMapping("/byName/{name}")
Understand and fix

2022-02-17 13:14 UTC, StanislavMilavitsky commented on api/src/java/com/epam/esm/controller/TagController.java
> +    @PostMapping(value = "/", consumes = "application/json")
Value in method not necessary.
In this method i need consumes, I'm saying that the method should accept only json it is work without consumes but body of request may be all types

2022-02-17 13:15 UTC, StanislavMilavitsky commented on api/src/java/com/epam/esm/exception/ControllerException.java
> +public class ControllerException extends Exception {
Fix java doc in this class. This exception response object of exception with message if body or parameters not valid

2022-02-17 13:18 UTC, StanislavMilavitsky commented on core/src/main/java/com/epam/esm/service/impl/GiftCertificateServiceImpl.java
> +        if (giftCertificates != null) {
FIx and deleted

2022-02-17 13:18 UTC, StanislavMilavitsky commented on core/src/main/java/com/epam/esm/service/impl/GiftCertificateServiceImpl.java
> +            logger.error("Sort by name exception!");
FIxed

2022-02-17 13:22 UTC, StanislavMilavitsky commented on core/src/test/java/com/epam/esm/dao/impl/TagDAOImplTest.java
> +    void delete() {
Fix

2022-02-17 13:26 UTC, StanislavMilavitsky commented on core/src/main/java/com/epam/esm/dao/impl/GiftCertificateDAOImpl.java
> +        return rows > 0L ? giftCertificateDTO.getId() : -1L;
It is returned, next step in services methode update use method dao.read, after dao.update

2022-02-17 13:31 UTC, StanislavMilavitsky commented on core/src/main/java/com/epam/esm/dao/impl/GiftCertificateDAOImpl.java
> +    public long update(GiftCertificateDTO giftCertificateDTO)  {
Ye,see and fix

2022-08-26 14:35 UTC, merged